Prefix all exceptions messages with "Pickle Error:"
Look like this:

```
error: Pickle Error:
  Missing step definition for "foo step"
2 errors
```

instead of:

```
error: Missing step definition for "foo step"
2 errors
```